#!/usr/bin/env python
from mlxtk.inout.dmat2 import read_raw
from mlxtk.plot.dmat2 import plot_dmat2
import argparse
import re
import os


def main():
    files = [file for file in os.listdir(os.getcwd()) if os.path.isfile(file)]
    default_file = None
    regex_dmat2 = re.compile("^dmat2_dof\d+_dof\d+_grid$")
    for file in files:
        if regex_dmat2.match(file):
            default_file = file
            break

    parser = argparse.ArgumentParser(
        description="Plot two-body density matrix")
    parser.add_argument(
        "-o",
        nargs="?",
        default=None,
        metavar="plot_file",
        help="file name of the generated plot")
    parser.add_argument(
        "dmat2",
        nargs="?",
        default=default_file,
        help="file the two-body density matrix (generated by qdtk_propagate.x)"
    )
    args = parser.parse_args()

    data = read_raw(args.dmat2)[0]
    if args.o:
        plot_dmat2(data).save(args.o)
    else:
        plot_dmat2(data).show()


if __name__ == "__main__":
    main()
