#!/usr/bin/env python
from mlxtk.inout.dmat1 import read_raw
from mlxtk.plot.dmat1 import plot_dmat1
import argparse
import re
import os


def main():
    files = [file for file in os.listdir(os.getcwd()) if os.path.isfile(file)]
    default_file = None
    regex_dmat1 = re.compile("^dmat_dof\d+_grid$")
    for file in files:
        if regex_dmat1.match(file):
            default_file = file
            break

    parser = argparse.ArgumentParser(
        description="Plot one-body density matrix")
    parser.add_argument(
        "-o",
        nargs="?",
        default=None,
        metavar="plot_file",
        help="file name of the generated plot",
    )
    parser.add_argument(
        "dmat1",
        nargs="?",
        default=default_file,
        help="file the one-body density matrix (generated by qdtk_propagate.x)",
    )
    args = parser.parse_args()

    data = read_raw(args.dmat1)[0]
    if args.o:
        plot_dmat1(data).save(args.o)
    else:
        plot_dmat1(data).show()


if __name__ == "__main__":
    main()
