#!/bin/bash
set -euf -o pipefail

FILES=`find mlxtk examples -name "*.py"`

echo "Run isort"
isort ${FILES} || exit

echo "Run autopep8"
autopep8 --in-place ${FILES} || exit

echo "Run yapf"
yapf --in-place --style=pep8 ${FILES} || exit
